.MODEL SMALL
.STACK 100H
.CODE

MAIN PROC    
    
    ;INPUT
    MOV AH, 1
    INT 21H
    MOV BL, AL 
    
    ;NEW LINE
    MOV AH, 2
    MOV DL, 13 ;SHIFT THE INPUT TO LEFT, IN HEXA 0DH  
    INT 21H
    MOV DL, 10 ;NEW LINW, IN HEXA 0AH
    INT 21H 
       
    ;OUTPUT
    ;MOV AH,2   ;ALREADY DECLEAR AH,2 FOR NEW LINW, SO WE CAN SKIP THIS LINE
    MOV DL, BL  
    INT 21H
    
    ;ENP RPOGRAM
    EXIT:
    MOV AH, 4CH
    INT 21H
    MAIN ENDP
END MAIN
