.MODEL SMALL
.STACK 100H

.DATA  ;DATA SEGMENT, VALUE INIT OR STRING
MSG1 DB 'RAHAT HOSSAN $' ; DOLLER SIGN AS LIKE NULL, STRING ENG HERE
MSG2 DB 'RAKIB HOSSAN $'

.CODE

MAIN PROC     
    
    ;INITIALIZE DATA SEGMENT
    MOV AX, @DATA
    MOV DS, AX    
    
    LEA DX, MSG1 ;LOAD EFFECTIVE ADDRESS
    MOV AH, 9    ;FOR STRING AH, 9 AS LIKE AH,2
    INT 21H
    
    MOV AH, 2
    MOV DL, 0DH
    INT 21H
    MOV DL, 0AH
    INT 21H
     
    LEA DX, MSG2 
    MOV AH, 9  
    INT 21H
    
    EXIT:
    MOV AH, 4CH
    INT 21H
    MAIN ENDP
END MAIN
